### ISSUE TITLE
Install GeoModels

### ISSUE THREAD

**Issue by eagomezdaza** [vmoprojs/GeoModels#3]
Hola... He seguido las instrucciones para instalar GeoModels y no he podido.

Me aparece el siguiente error.

installation of package ‘/tmp/Rtmpmneh8Z/file2b56cd7198dbdc/GeoModels_1.0.3-4.tar.gz’ had non-zero exit status

**Comment by vmoprojs** [comment]
Hola,

Hemos lanzado una nueva versión del paquete. Cuéntame si aún tienes problemas de instalación:

`install.packages("GeoModels")`
